import type { MarketplaceAgent } from './marketplaceTypes'

export const MOCK_AGENTS: MarketplaceAgent[] = [
  {
    id: 'agent-translator',
    name: '다국어 번역 전문가',
    description: '한/영/일/중 4개 언어 고품질 번역',
    longDescription:
      '현대차그룹 전문 용어를 반영한 고품질 번역 에이전트입니다. 기술 문서, 마케팅 자료, 이메일 등 다양한 형식을 지원합니다.',
    author: 'H Chat Team',
    category: 'translation',
    icon: '🌐',
    iconColor: '#3B82F6',
    version: '2.1.0',
    rating: 4.8,
    reviewCount: 342,
    installs: 8500,
    model: 'GPT-4o',
    tools: [{ id: 't1', name: '언어 감지', description: '입력 텍스트의 언어를 자동 감지' }],
    systemPrompt: 'You are a professional translator...',
    changelog: ['v2.1.0: 중국어 간체/번체 지원', 'v2.0.0: 일본어 추가', 'v1.0.0: 초기 출시'],
    tags: ['번역', '다국어', '문서'],
    createdAt: '2025-06-01',
    updatedAt: '2026-02-15',
  },
  {
    id: 'agent-code-review',
    name: '코드 리뷰어',
    description: '코드 품질, 보안, 성능 자동 검토',
    longDescription:
      '소스 코드를 분석하여 버그, 보안 취약점, 성능 이슈를 식별합니다. TypeScript, Python, Java 등 주요 언어를 지원합니다.',
    author: 'DevOps Lab',
    category: 'development',
    icon: '🔍',
    iconColor: '#8B5CF6',
    version: '3.0.1',
    rating: 4.9,
    reviewCount: 567,
    installs: 12300,
    model: 'Claude 3.5 Sonnet',
    tools: [
      { id: 't1', name: 'AST 분석', description: '코드 구조 분석' },
      { id: 't2', name: '보안 스캔', description: 'OWASP Top 10 취약점 검사' },
    ],
    systemPrompt: 'You are an expert code reviewer...',
    changelog: ['v3.0.1: React 19 지원', 'v3.0.0: Python 3.12 지원'],
    tags: ['코드리뷰', '보안', '품질'],
    createdAt: '2025-03-15',
    updatedAt: '2026-03-01',
  },
  {
    id: 'agent-doc-summary',
    name: '문서 요약 마스터',
    description: '긴 문서를 핵심 요점으로 정리',
    longDescription:
      '회의록, 보고서, 기술 문서 등 긴 텍스트를 구조화된 요약으로 변환합니다. 핵심 키워드 추출과 액션 아이템 정리를 지원합니다.',
    author: 'H Chat Team',
    category: 'productivity',
    icon: '📋',
    iconColor: '#10B981',
    version: '1.5.0',
    rating: 4.6,
    reviewCount: 198,
    installs: 6200,
    model: 'GPT-4o-mini',
    tools: [{ id: 't1', name: '키워드 추출', description: '핵심 키워드 자동 추출' }],
    systemPrompt: 'You are an expert document summarizer...',
    changelog: ['v1.5.0: 표 형식 요약 추가', 'v1.0.0: 초기 출시'],
    tags: ['요약', '문서', '생산성'],
    createdAt: '2025-08-20',
    updatedAt: '2026-01-10',
  },
  {
    id: 'agent-data-analyst',
    name: '데이터 분석가',
    description: 'CSV/Excel 데이터 분석 및 시각화 제안',
    longDescription:
      '데이터 파일을 분석하여 트렌드, 이상치, 상관관계를 발견합니다. 차트 유형 추천과 인사이트 자동 생성을 지원합니다.',
    author: 'Analytics Team',
    category: 'analysis',
    icon: '📊',
    iconColor: '#F59E0B',
    version: '2.0.0',
    rating: 4.7,
    reviewCount: 245,
    installs: 5800,
    model: 'GPT-4o',
    tools: [
      { id: 't1', name: '데이터 파싱', description: 'CSV/Excel 자동 파싱' },
      { id: 't2', name: '통계 분석', description: '기술 통계 자동 계산' },
    ],
    systemPrompt: 'You are a data analysis expert...',
    changelog: ['v2.0.0: Excel 지원', 'v1.0.0: CSV 분석'],
    tags: ['데이터', '분석', '시각화'],
    createdAt: '2025-05-10',
    updatedAt: '2026-02-20',
  },
  {
    id: 'agent-email-writer',
    name: '비즈니스 이메일 작성기',
    description: '상황별 전문 이메일 초안 작성',
    longDescription:
      '비즈니스 상황에 맞는 전문적인 이메일을 작성합니다. 톤 조절, 다국어 지원, 후속 메일 추천 기능을 제공합니다.',
    author: 'Comm Team',
    category: 'business',
    icon: '✉️',
    iconColor: '#EF4444',
    version: '1.3.0',
    rating: 4.5,
    reviewCount: 156,
    installs: 4100,
    model: 'Claude 3.5 Haiku',
    tools: [],
    systemPrompt: 'You are an expert business email writer...',
    changelog: ['v1.3.0: CC/BCC 제안', 'v1.0.0: 초기 출시'],
    tags: ['이메일', '비즈니스', '커뮤니케이션'],
    createdAt: '2025-09-01',
    updatedAt: '2026-01-20',
  },
  {
    id: 'agent-image-gen',
    name: '이미지 생성 어시스턴트',
    description: '텍스트 설명으로 이미지 생성 프롬프트 최적화',
    longDescription:
      '사용자의 텍스트 설명을 분석하여 DALL-E, Midjourney 등에 최적화된 프롬프트를 생성합니다.',
    author: 'Creative Lab',
    category: 'creative',
    icon: '🎨',
    iconColor: '#EC4899',
    version: '1.0.0',
    rating: 4.3,
    reviewCount: 89,
    installs: 2400,
    model: 'GPT-4o',
    tools: [],
    systemPrompt: 'You are an image generation prompt expert...',
    changelog: ['v1.0.0: 초기 출시'],
    tags: ['이미지', '프롬프트', '크리에이티브'],
    createdAt: '2026-01-15',
    updatedAt: '2026-02-10',
  },
  {
    id: 'agent-meeting-note',
    name: '회의록 작성 도우미',
    description: '회의 내용을 구조화된 회의록으로 변환',
    longDescription:
      '음성 트랜스크립트나 메모를 바탕으로 전문적인 회의록을 작성합니다. 액션 아이템, 결정 사항, 참석자 정리를 자동화합니다.',
    author: 'H Chat Team',
    category: 'productivity',
    icon: '📝',
    iconColor: '#6366F1',
    version: '1.2.0',
    rating: 4.7,
    reviewCount: 178,
    installs: 5100,
    model: 'GPT-4o-mini',
    tools: [{ id: 't1', name: '액션 아이템 추출', description: '할 일 자동 정리' }],
    systemPrompt: 'You are a meeting notes specialist...',
    changelog: ['v1.2.0: 다국어 회의 지원', 'v1.0.0: 초기 출시'],
    tags: ['회의록', '생산성', '자동화'],
    createdAt: '2025-07-01',
    updatedAt: '2026-02-05',
  },
  {
    id: 'agent-sql-helper',
    name: 'SQL 쿼리 도우미',
    description: '자연어로 SQL 쿼리 생성 및 최적화',
    longDescription:
      '자연어 질문을 SQL 쿼리로 변환하고, 기존 쿼리의 성능을 최적화합니다. MySQL, PostgreSQL, BigQuery를 지원합니다.',
    author: 'Data Engineering',
    category: 'development',
    icon: '🗄️',
    iconColor: '#0EA5E9',
    version: '2.1.0',
    rating: 4.8,
    reviewCount: 312,
    installs: 7200,
    model: 'Claude 3.5 Sonnet',
    tools: [{ id: 't1', name: 'SQL 검증', description: '쿼리 문법 자동 검증' }],
    systemPrompt: 'You are an expert SQL developer...',
    changelog: ['v2.1.0: BigQuery 지원', 'v2.0.0: 쿼리 최적화'],
    tags: ['SQL', '데이터베이스', '개발'],
    createdAt: '2025-04-20',
    updatedAt: '2026-03-01',
  },
  {
    id: 'agent-tutor',
    name: 'AI 학습 튜터',
    description: '개인 맞춤형 학습 도우미',
    longDescription: '학습자의 수준에 맞춰 설명하고, 퀴즈를 생성하며, 복습 스케줄을 제안합니다.',
    author: 'Education Team',
    category: 'education',
    icon: '🎓',
    iconColor: '#14B8A6',
    version: '1.1.0',
    rating: 4.6,
    reviewCount: 134,
    installs: 3800,
    model: 'GPT-4o',
    tools: [{ id: 't1', name: '퀴즈 생성', description: '학습 내용 기반 퀴즈' }],
    systemPrompt: 'You are a patient and adaptive tutor...',
    changelog: ['v1.1.0: 퀴즈 기능', 'v1.0.0: 초기 출시'],
    tags: ['교육', '학습', '퀴즈'],
    createdAt: '2025-10-01',
    updatedAt: '2026-01-15',
  },
  {
    id: 'agent-report-gen',
    name: '보고서 생성기',
    description: '데이터 기반 전문 보고서 자동 작성',
    longDescription:
      '수집된 데이터와 분석 결과를 바탕으로 전문적인 보고서를 자동 생성합니다. 차트 삽입, 요약, 결론 도출을 지원합니다.',
    author: 'H Chat Team',
    category: 'business',
    icon: '📄',
    iconColor: '#8B5CF6',
    version: '1.0.0',
    rating: 4.4,
    reviewCount: 76,
    installs: 2100,
    model: 'GPT-4o',
    tools: [],
    systemPrompt: 'You are a professional report writer...',
    changelog: ['v1.0.0: 초기 출시'],
    tags: ['보고서', '비즈니스', '자동화'],
    createdAt: '2026-01-20',
    updatedAt: '2026-02-28',
  },
]
