#!/bin/bash
# check-bundle-size.sh — Measure each app's build output size against budget
#
# Static Export apps:  measures entire out/ directory
# SSR apps:            measures .next/static/ directory (client bundles only)
#
# Exit codes:
#   0 — all apps within budget
#   1 — one or more apps exceed budget (warn only, non-blocking)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BUDGETS_FILE="$SCRIPT_DIR/bundle-budgets.json"

# Colors for terminal output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# Track overall status
HAS_WARNING=0
REPORT_LINES=()

header() {
  echo ""
  echo -e "${BOLD}========================================${NC}"
  echo -e "${BOLD} Bundle Size Report${NC}"
  echo -e "${BOLD}========================================${NC}"
  echo ""
}

# Get directory size in KB (cross-platform: macOS + Linux)
get_size_kb() {
  local dir="$1"
  if [[ ! -d "$dir" ]]; then
    echo "0"
    return
  fi

  local size_bytes
  if [[ "$(uname)" == "Darwin" ]]; then
    # macOS: stat -f%z for each file, sum them
    size_bytes=$(find "$dir" -type f -exec stat -f%z {} + 2>/dev/null | awk '{s+=$1} END {printf "%.0f", s}')
  else
    # Linux: du -sb for total bytes
    size_bytes=$(du -sb "$dir" 2>/dev/null | awk '{print $1}')
  fi

  if [[ -z "$size_bytes" || "$size_bytes" == "0" ]]; then
    echo "0"
  else
    echo $(( (size_bytes + 1023) / 1024 ))
  fi
}

# Format size for display
format_size() {
  local kb=$1
  if (( kb >= 1024 )); then
    echo "$(awk "BEGIN {printf \"%.1f\", $kb/1024}")MB"
  else
    echo "${kb}KB"
  fi
}

# Parse JSON budgets (portable: no jq dependency)
parse_budgets() {
  # Extract app names from JSON keys
  grep -o '"[a-z-]*":' "$BUDGETS_FILE" | tr -d '":' || true
}

get_json_value() {
  local app="$1"
  local key="$2"
  # Simple JSON value extraction without jq
  sed -n "/${app}/,/}/p" "$BUDGETS_FILE" | grep "\"${key}\"" | head -1 | sed 's/.*: *"\{0,1\}\([^",}]*\)"\{0,1\}.*/\1/'
}

check_app() {
  local app="$1"
  local max_kb
  local dir
  local app_type

  max_kb=$(get_json_value "$app" "maxSizeKB")
  dir=$(get_json_value "$app" "dir")
  app_type=$(get_json_value "$app" "type")

  local full_dir="$ROOT_DIR/$dir"

  if [[ ! -d "$full_dir" ]]; then
    local line
    line=$(printf "  %-14s %s" "$app" "SKIP (not built)")
    echo -e "  ${CYAN}$(printf '%-14s' "$app")${NC} SKIP (not built)"
    REPORT_LINES+=("| $app | - | ${max_kb}KB | SKIP (not built) |")
    return
  fi

  local actual_kb
  actual_kb=$(get_size_kb "$full_dir")
  local actual_formatted
  actual_formatted=$(format_size "$actual_kb")
  local max_formatted
  max_formatted=$(format_size "$max_kb")
  local pct
  pct=$(awk "BEGIN {printf \"%.0f\", ($actual_kb/$max_kb)*100}")

  local status_icon status_text
  if (( actual_kb > max_kb )); then
    status_icon="${RED}OVER${NC}"
    status_text="OVER BUDGET (+$(format_size $((actual_kb - max_kb))))"
    HAS_WARNING=1
    REPORT_LINES+=("| $app | $actual_formatted ($pct%) | $max_formatted | :warning: $status_text |")
  elif (( actual_kb > max_kb * 80 / 100 )); then
    status_icon="${YELLOW}WARN${NC}"
    status_text="Near limit ($pct%)"
    REPORT_LINES+=("| $app | $actual_formatted ($pct%) | $max_formatted | :large_orange_diamond: $status_text |")
  else
    status_icon="${GREEN}OK${NC}"
    status_text="OK ($pct%)"
    REPORT_LINES+=("| $app | $actual_formatted ($pct%) | $max_formatted | :white_check_mark: $status_text |")
  fi

  printf "  ${CYAN}%-14s${NC} %10s / %10s  [%3s%%]  %b\n" "$app" "$actual_formatted" "$max_formatted" "$pct" "$status_icon"
}

# Generate markdown report for CI (PR comment)
generate_markdown_report() {
  local output_file="$ROOT_DIR/bundle-report.md"

  {
    echo "## Bundle Size Report"
    echo ""
    echo "| App | Size (% of budget) | Budget | Status |"
    echo "|-----|-------------------|--------|--------|"
    for line in "${REPORT_LINES[@]}"; do
      echo "$line"
    done
    echo ""
    echo "_Generated by \`scripts/check-bundle-size.sh\`_"
  } > "$output_file"

  echo ""
  echo -e "${BOLD}Markdown report:${NC} $output_file"
}

# ── Main ──

header

APPS=$(parse_budgets)

for app in $APPS; do
  check_app "$app"
done

# Generate markdown report for CI usage
generate_markdown_report

echo ""
if (( HAS_WARNING == 1 )); then
  echo -e "${YELLOW}WARNING: One or more apps exceed their bundle budget.${NC}"
  echo -e "${YELLOW}Review the report above and consider optimizing.${NC}"
  # Exit 0 — warn only, not a hard fail
  exit 0
else
  echo -e "${GREEN}All apps within budget.${NC}"
  exit 0
fi
