import type { LLMModel, APIKey, UsageStat, ModelUsage } from './types';

export const models: LLMModel[] = [
  // OpenAI - Popular models
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    providerIcon: '🤖',
    category: 'chat',
    inputPrice: 3300,
    outputPrice: 13200,
    contextWindow: 128000,
    maxOutput: 16384,
    latency: '0.8초',
    isPopular: true,
  },
  {
    id: 'gpt-4-1',
    name: 'GPT-4.1',
    provider: 'OpenAI',
    providerIcon: '🤖',
    category: 'chat',
    inputPrice: 4000,
    outputPrice: 16000,
    contextWindow: 200000,
    maxOutput: 32768,
    latency: '1.2초',
    isPopular: true,
  },
  {
    id: 'gpt-4-1-nano',
    name: 'GPT-4.1 nano',
    provider: 'OpenAI',
    providerIcon: '🤖',
    category: 'chat',
    inputPrice: 200,
    outputPrice: 800,
    contextWindow: 128000,
    maxOutput: 16384,
    latency: '0.4초',
  },
  {
    id: 'gpt-4-1-mini',
    name: 'GPT-4.1 mini',
    provider: 'OpenAI',
    providerIcon: '🤖',
    category: 'chat',
    inputPrice: 200,
    outputPrice: 800,
    contextWindow: 128000,
    maxOutput: 16384,
    latency: '0.5초',
    isPopular: true,
  },
  {
    id: 'o1',
    name: 'o1',
    provider: 'OpenAI',
    providerIcon: '🤖',
    category: 'chat',
    inputPrice: 19800,
    outputPrice: 79200,
    contextWindow: 200000,
    maxOutput: 100000,
    latency: '5.2초',
  },
  {
    id: 'o3',
    name: 'o3',
    provider: 'OpenAI',
    providerIcon: '🤖',
    category: 'chat',
    inputPrice: 13200,
    outputPrice: 52800,
    contextWindow: 200000,
    maxOutput: 100000,
    latency: '4.1초',
  },
  {
    id: 'o4-mini',
    name: 'o4-mini',
    provider: 'OpenAI',
    providerIcon: '🤖',
    category: 'chat',
    inputPrice: 440,
    outputPrice: 1760,
    contextWindow: 128000,
    maxOutput: 65536,
    latency: '1.8초',
  },
  {
    id: 'dall-e-3',
    name: 'DALL-E 3',
    provider: 'OpenAI',
    providerIcon: '🤖',
    category: 'image',
    inputPrice: 52800,
    outputPrice: 0,
    contextWindow: 4000,
    maxOutput: 1,
    latency: '12초',
    isPopular: true,
  },
  {
    id: 'whisper-1',
    name: 'Whisper',
    provider: 'OpenAI',
    providerIcon: '🤖',
    category: 'audio',
    inputPrice: 7920,
    outputPrice: 0,
    contextWindow: 25000000,
    maxOutput: 4096,
    latency: '3.5초',
  },
  {
    id: 'text-embedding-3-large',
    name: 'text-embedding-3-large',
    provider: 'OpenAI',
    providerIcon: '🤖',
    category: 'embedding',
    inputPrice: 172,
    outputPrice: 0,
    contextWindow: 8191,
    maxOutput: 3072,
    latency: '0.2초',
  },
  {
    id: 'text-embedding-3-small',
    name: 'text-embedding-3-small',
    provider: 'OpenAI',
    providerIcon: '🤖',
    category: 'embedding',
    inputPrice: 26,
    outputPrice: 0,
    contextWindow: 8191,
    maxOutput: 1536,
    latency: '0.15초',
  },
  {
    id: 'gpt-3-5-turbo',
    name: 'GPT-3.5 Turbo',
    provider: 'OpenAI',
    providerIcon: '🤖',
    category: 'chat',
    inputPrice: 660,
    outputPrice: 1320,
    contextWindow: 16385,
    maxOutput: 4096,
    latency: '0.5초',
  },
  {
    id: 'gpt-3-5-turbo-16k',
    name: 'GPT-3.5 Turbo 16k',
    provider: 'OpenAI',
    providerIcon: '🤖',
    category: 'chat',
    inputPrice: 3960,
    outputPrice: 5280,
    contextWindow: 16385,
    maxOutput: 4096,
    latency: '0.7초',
  },

  // Anthropic - Popular models
  {
    id: 'claude-opus-4-6',
    name: 'Claude Opus 4.6',
    provider: 'Anthropic',
    providerIcon: '🧠',
    category: 'chat',
    inputPrice: 19800,
    outputPrice: 79200,
    contextWindow: 200000,
    maxOutput: 16384,
    latency: '2.1초',
    isPopular: true,
  },
  {
    id: 'claude-sonnet-4-5',
    name: 'Claude Sonnet 4.5',
    provider: 'Anthropic',
    providerIcon: '🧠',
    category: 'chat',
    inputPrice: 3960,
    outputPrice: 19800,
    contextWindow: 200000,
    maxOutput: 16384,
    latency: '1.1초',
    isPopular: true,
  },
  {
    id: 'claude-haiku-4-5',
    name: 'Claude Haiku 4.5',
    provider: 'Anthropic',
    providerIcon: '🧠',
    category: 'chat',
    inputPrice: 330,
    outputPrice: 1650,
    contextWindow: 200000,
    maxOutput: 8192,
    latency: '0.6초',
  },
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    providerIcon: '🧠',
    category: 'chat',
    inputPrice: 3960,
    outputPrice: 19800,
    contextWindow: 200000,
    maxOutput: 8192,
    latency: '1.3초',
  },
  {
    id: 'claude-instant-1-2',
    name: 'Claude Instant 1.2',
    provider: 'Anthropic',
    providerIcon: '🧠',
    category: 'chat',
    inputPrice: 1056,
    outputPrice: 3168,
    contextWindow: 100000,
    maxOutput: 4096,
    latency: '0.6초',
  },
  {
    id: 'claude-2-1',
    name: 'Claude 2.1',
    provider: 'Anthropic',
    providerIcon: '🧠',
    category: 'chat',
    inputPrice: 10560,
    outputPrice: 31680,
    contextWindow: 200000,
    maxOutput: 4096,
    latency: '1.8초',
  },
  {
    id: 'claude-2',
    name: 'Claude 2',
    provider: 'Anthropic',
    providerIcon: '🧠',
    category: 'chat',
    inputPrice: 10560,
    outputPrice: 31680,
    contextWindow: 100000,
    maxOutput: 4096,
    latency: '1.9초',
  },

  // Google - Popular models
  {
    id: 'gemini-2-5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'Google',
    providerIcon: '💎',
    category: 'chat',
    inputPrice: 1650,
    outputPrice: 6600,
    contextWindow: 1000000,
    maxOutput: 8192,
    latency: '1.5초',
    isPopular: true,
  },
  {
    id: 'gemini-2-5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'Google',
    providerIcon: '💎',
    category: 'chat',
    inputPrice: 105,
    outputPrice: 420,
    contextWindow: 1000000,
    maxOutput: 8192,
    latency: '0.4초',
  },
  {
    id: 'gemini-2-0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'Google',
    providerIcon: '💎',
    category: 'chat',
    inputPrice: 79,
    outputPrice: 316,
    contextWindow: 1000000,
    maxOutput: 8192,
    latency: '0.5초',
  },
  {
    id: 'gemma-3-27b',
    name: 'Gemma 3 27B',
    provider: 'Google',
    providerIcon: '💎',
    category: 'chat',
    inputPrice: 360,
    outputPrice: 1440,
    contextWindow: 128000,
    maxOutput: 8192,
    latency: '0.9초',
  },
  {
    id: 'gemma-3-9b',
    name: 'Gemma 3 9B',
    provider: 'Google',
    providerIcon: '💎',
    category: 'chat',
    inputPrice: 132,
    outputPrice: 528,
    contextWindow: 128000,
    maxOutput: 8192,
    latency: '0.6초',
  },
  {
    id: 'palm-2',
    name: 'PaLM 2',
    provider: 'Google',
    providerIcon: '💎',
    category: 'chat',
    inputPrice: 528,
    outputPrice: 1056,
    contextWindow: 8192,
    maxOutput: 1024,
    latency: '0.9초',
  },
  {
    id: 'text-bison',
    name: 'Text Bison',
    provider: 'Google',
    providerIcon: '💎',
    category: 'completion',
    inputPrice: 528,
    outputPrice: 528,
    contextWindow: 8192,
    maxOutput: 1024,
    latency: '0.7초',
  },
  {
    id: 'code-bison',
    name: 'Code Bison',
    provider: 'Google',
    providerIcon: '💎',
    category: 'code',
    inputPrice: 528,
    outputPrice: 528,
    contextWindow: 6144,
    maxOutput: 1024,
    latency: '0.8초',
  },
  {
    id: 'flan-t5-xxl',
    name: 'FLAN-T5 XXL',
    provider: 'Google',
    providerIcon: '💎',
    category: 'completion',
    inputPrice: 1320,
    outputPrice: 1320,
    contextWindow: 512,
    maxOutput: 512,
    latency: '0.9초',
  },
  {
    id: 'flan-ul2',
    name: 'FLAN-UL2',
    provider: 'Google',
    providerIcon: '💎',
    category: 'completion',
    inputPrice: 1320,
    outputPrice: 1320,
    contextWindow: 2048,
    maxOutput: 2048,
    latency: '1.0초',
  },

  // Meta - Popular models
  {
    id: 'llama-4-scout',
    name: 'Llama 4 Scout',
    provider: 'Meta',
    providerIcon: '🦙',
    category: 'chat',
    inputPrice: 660,
    outputPrice: 2640,
    contextWindow: 128000,
    maxOutput: 16384,
    latency: '1.0초',
  },
  {
    id: 'llama-4-maverick',
    name: 'Llama 4 Maverick',
    provider: 'Meta',
    providerIcon: '🦙',
    category: 'chat',
    inputPrice: 1320,
    outputPrice: 5280,
    contextWindow: 128000,
    maxOutput: 16384,
    latency: '1.4초',
  },
  {
    id: 'llama-3-3-70b',
    name: 'Llama 3.3 70B',
    provider: 'Meta',
    providerIcon: '🦙',
    category: 'chat',
    inputPrice: 528,
    outputPrice: 792,
    contextWindow: 128000,
    maxOutput: 32768,
    latency: '1.2초',
    isPopular: true,
  },
  {
    id: 'llama-3-1-405b',
    name: 'Llama 3.1 405B',
    provider: 'Meta',
    providerIcon: '🦙',
    category: 'chat',
    inputPrice: 3520,
    outputPrice: 3520,
    contextWindow: 128000,
    maxOutput: 16384,
    latency: '2.8초',
  },
  {
    id: 'llama-3-1-70b',
    name: 'Llama 3.1 70B',
    provider: 'Meta',
    providerIcon: '🦙',
    category: 'chat',
    inputPrice: 528,
    outputPrice: 792,
    contextWindow: 128000,
    maxOutput: 16384,
    latency: '1.1초',
  },
  {
    id: 'llama-2-70b',
    name: 'Llama 2 70B',
    provider: 'Meta',
    providerIcon: '🦙',
    category: 'chat',
    inputPrice: 900,
    outputPrice: 900,
    contextWindow: 4096,
    maxOutput: 4096,
    latency: '1.3초',
  },
  {
    id: 'llama-2-13b',
    name: 'Llama 2 13B',
    provider: 'Meta',
    providerIcon: '🦙',
    category: 'chat',
    inputPrice: 300,
    outputPrice: 300,
    contextWindow: 4096,
    maxOutput: 4096,
    latency: '0.8초',
  },
  {
    id: 'llama-2-7b',
    name: 'Llama 2 7B',
    provider: 'Meta',
    providerIcon: '🦙',
    category: 'chat',
    inputPrice: 200,
    outputPrice: 200,
    contextWindow: 4096,
    maxOutput: 4096,
    latency: '0.5초',
  },
  {
    id: 'code-llama-34b',
    name: 'Code Llama 34B',
    provider: 'Meta',
    providerIcon: '🦙',
    category: 'code',
    inputPrice: 792,
    outputPrice: 792,
    contextWindow: 16384,
    maxOutput: 16384,
    latency: '1.0초',
  },

  // Mistral - Popular model
  {
    id: 'mistral-large-2',
    name: 'Mistral Large 2',
    provider: 'Mistral',
    providerIcon: '🌬️',
    category: 'chat',
    inputPrice: 3960,
    outputPrice: 13200,
    contextWindow: 128000,
    maxOutput: 16384,
    latency: '1.3초',
  },
  {
    id: 'mistral-medium',
    name: 'Mistral Medium',
    provider: 'Mistral',
    providerIcon: '🌬️',
    category: 'chat',
    inputPrice: 3564,
    outputPrice: 11880,
    contextWindow: 32000,
    maxOutput: 8192,
    latency: '1.0초',
  },
  {
    id: 'mistral-small',
    name: 'Mistral Small',
    provider: 'Mistral',
    providerIcon: '🌬️',
    category: 'chat',
    inputPrice: 1320,
    outputPrice: 3960,
    contextWindow: 32000,
    maxOutput: 8192,
    latency: '0.7초',
  },
  {
    id: 'codestral',
    name: 'Codestral',
    provider: 'Mistral',
    providerIcon: '🌬️',
    category: 'code',
    inputPrice: 1320,
    outputPrice: 3960,
    contextWindow: 32000,
    maxOutput: 8192,
    latency: '0.9초',
    isPopular: true,
  },
  {
    id: 'mistral-7b',
    name: 'Mistral 7B',
    provider: 'Mistral',
    providerIcon: '🌬️',
    category: 'chat',
    inputPrice: 264,
    outputPrice: 264,
    contextWindow: 32000,
    maxOutput: 8192,
    latency: '0.5초',
  },
  {
    id: 'mixtral-8x7b',
    name: 'Mixtral 8x7B',
    provider: 'Mistral',
    providerIcon: '🌬️',
    category: 'chat',
    inputPrice: 594,
    outputPrice: 594,
    contextWindow: 32000,
    maxOutput: 8192,
    latency: '0.8초',
  },

  // Cohere
  {
    id: 'command-r-plus',
    name: 'Command R+',
    provider: 'Cohere',
    providerIcon: '🔮',
    category: 'chat',
    inputPrice: 3960,
    outputPrice: 19800,
    contextWindow: 128000,
    maxOutput: 4096,
    latency: '1.6초',
  },
  {
    id: 'command-r',
    name: 'Command R',
    provider: 'Cohere',
    providerIcon: '🔮',
    category: 'chat',
    inputPrice: 660,
    outputPrice: 1980,
    contextWindow: 128000,
    maxOutput: 4096,
    latency: '1.1초',
  },
  {
    id: 'embed-english-v3',
    name: 'Embed English v3',
    provider: 'Cohere',
    providerIcon: '🔮',
    category: 'embedding',
    inputPrice: 132,
    outputPrice: 0,
    contextWindow: 512,
    maxOutput: 1024,
    latency: '0.1초',
  },
  {
    id: 'embed-multilingual-v3',
    name: 'Embed Multilingual v3',
    provider: 'Cohere',
    providerIcon: '🔮',
    category: 'embedding',
    inputPrice: 132,
    outputPrice: 0,
    contextWindow: 512,
    maxOutput: 1024,
    latency: '0.1초',
  },

  // DeepSeek
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3',
    provider: 'DeepSeek',
    providerIcon: '🔍',
    category: 'chat',
    inputPrice: 364,
    outputPrice: 1452,
    contextWindow: 64000,
    maxOutput: 8192,
    latency: '1.0초',
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'DeepSeek',
    providerIcon: '🔍',
    category: 'chat',
    inputPrice: 728,
    outputPrice: 2904,
    contextWindow: 64000,
    maxOutput: 8192,
    latency: '2.3초',
  },

  // 기타 providers
  {
    id: 'qwen-2-5-72b',
    name: 'Qwen 2.5 72B',
    provider: 'Alibaba',
    providerIcon: '🐉',
    category: 'chat',
    inputPrice: 594,
    outputPrice: 594,
    contextWindow: 128000,
    maxOutput: 8192,
    latency: '1.1초',
  },
  {
    id: 'yi-large',
    name: 'Yi Large',
    provider: '01.AI',
    providerIcon: '🚀',
    category: 'chat',
    inputPrice: 3960,
    outputPrice: 13200,
    contextWindow: 32000,
    maxOutput: 4096,
    latency: '1.5초',
  },
  {
    id: 'yi-34b',
    name: 'Yi 34B',
    provider: '01.AI',
    providerIcon: '🚀',
    category: 'chat',
    inputPrice: 792,
    outputPrice: 792,
    contextWindow: 4096,
    maxOutput: 4096,
    latency: '1.0초',
  },
  {
    id: 'yi-6b',
    name: 'Yi 6B',
    provider: '01.AI',
    providerIcon: '🚀',
    category: 'chat',
    inputPrice: 200,
    outputPrice: 200,
    contextWindow: 4096,
    maxOutput: 4096,
    latency: '0.5초',
  },
  {
    id: 'solar-1-mini',
    name: 'Solar 1 Mini',
    provider: 'Upstage',
    providerIcon: '☀️',
    category: 'chat',
    inputPrice: 264,
    outputPrice: 1056,
    contextWindow: 32000,
    maxOutput: 4096,
    latency: '0.6초',
  },
  {
    id: 'phi-3-medium',
    name: 'Phi-3 Medium',
    provider: 'Microsoft',
    providerIcon: '🪟',
    category: 'chat',
    inputPrice: 264,
    outputPrice: 1056,
    contextWindow: 128000,
    maxOutput: 4096,
    latency: '0.7초',
  },
  {
    id: 'orca-2-13b',
    name: 'Orca 2 13B',
    provider: 'Microsoft',
    providerIcon: '🪟',
    category: 'chat',
    inputPrice: 300,
    outputPrice: 300,
    contextWindow: 4096,
    maxOutput: 4096,
    latency: '0.8초',
  },
  {
    id: 'orca-2-7b',
    name: 'Orca 2 7B',
    provider: 'Microsoft',
    providerIcon: '🪟',
    category: 'chat',
    inputPrice: 264,
    outputPrice: 264,
    contextWindow: 4096,
    maxOutput: 4096,
    latency: '0.6초',
  },
  {
    id: 'falcon-180b',
    name: 'Falcon 180B',
    provider: 'TII',
    providerIcon: '🦅',
    category: 'chat',
    inputPrice: 2640,
    outputPrice: 7920,
    contextWindow: 2048,
    maxOutput: 2048,
    latency: '2.0초',
  },
  {
    id: 'stable-diffusion-xl',
    name: 'Stable Diffusion XL',
    provider: 'Stability AI',
    providerIcon: '🎨',
    category: 'image',
    inputPrice: 13200,
    outputPrice: 0,
    contextWindow: 77,
    maxOutput: 1,
    latency: '8.5초',
  },
  {
    id: 'stable-code',
    name: 'Stable Code',
    provider: 'Stability AI',
    providerIcon: '🎨',
    category: 'code',
    inputPrice: 660,
    outputPrice: 2640,
    contextWindow: 16000,
    maxOutput: 4096,
    latency: '1.1초',
  },
  {
    id: 'stablelm-tuned-alpha-7b',
    name: 'StableLM Tuned Alpha 7B',
    provider: 'Stability AI',
    providerIcon: '🎨',
    category: 'chat',
    inputPrice: 264,
    outputPrice: 264,
    contextWindow: 4096,
    maxOutput: 4096,
    latency: '0.6초',
  },
  {
    id: 'wizardcoder-34b',
    name: 'WizardCoder 34B',
    provider: 'WizardLM',
    providerIcon: '🧙',
    category: 'code',
    inputPrice: 792,
    outputPrice: 792,
    contextWindow: 8192,
    maxOutput: 8192,
    latency: '1.1초',
  },
  {
    id: 'phind-codellama-34b',
    name: 'Phind CodeLlama 34B',
    provider: 'Phind',
    providerIcon: '🔎',
    category: 'code',
    inputPrice: 792,
    outputPrice: 792,
    contextWindow: 16384,
    maxOutput: 16384,
    latency: '1.0초',
  },
  {
    id: 'airoboros-70b',
    name: 'Airoboros 70B',
    provider: 'Jondurbin',
    providerIcon: '🤖',
    category: 'chat',
    inputPrice: 900,
    outputPrice: 900,
    contextWindow: 4096,
    maxOutput: 4096,
    latency: '1.3초',
  },
  {
    id: 'nous-hermes-llama2-13b',
    name: 'Nous Hermes Llama2 13B',
    provider: 'NousResearch',
    providerIcon: '📚',
    category: 'chat',
    inputPrice: 300,
    outputPrice: 300,
    contextWindow: 4096,
    maxOutput: 4096,
    latency: '0.8초',
  },
  {
    id: 'mythomax-13b',
    name: 'MythoMax 13B',
    provider: 'Gryphe',
    providerIcon: '🐉',
    category: 'chat',
    inputPrice: 300,
    outputPrice: 300,
    contextWindow: 4096,
    maxOutput: 4096,
    latency: '0.7초',
  },
  {
    id: 'openhermes-2-5-mistral-7b',
    name: 'OpenHermes 2.5 Mistral 7B',
    provider: 'Teknium',
    providerIcon: '📖',
    category: 'chat',
    inputPrice: 264,
    outputPrice: 264,
    contextWindow: 8192,
    maxOutput: 8192,
    latency: '0.6초',
  },
  {
    id: 'dolphin-2-6-mixtral-8x7b',
    name: 'Dolphin 2.6 Mixtral 8x7B',
    provider: 'Cognitive Computations',
    providerIcon: '🐬',
    category: 'chat',
    inputPrice: 594,
    outputPrice: 594,
    contextWindow: 32000,
    maxOutput: 8192,
    latency: '0.9초',
  },
  {
    id: 'zephyr-7b-beta',
    name: 'Zephyr 7B Beta',
    provider: 'HuggingFace',
    providerIcon: '🤗',
    category: 'chat',
    inputPrice: 264,
    outputPrice: 264,
    contextWindow: 4096,
    maxOutput: 4096,
    latency: '0.5초',
  },
  {
    id: 'openchat-3-5',
    name: 'OpenChat 3.5',
    provider: 'OpenChat',
    providerIcon: '💬',
    category: 'chat',
    inputPrice: 264,
    outputPrice: 264,
    contextWindow: 8192,
    maxOutput: 8192,
    latency: '0.6초',
  },
  {
    id: 'starling-7b-alpha',
    name: 'Starling 7B Alpha',
    provider: 'Berkeley',
    providerIcon: '🐦',
    category: 'chat',
    inputPrice: 264,
    outputPrice: 264,
    contextWindow: 8192,
    maxOutput: 8192,
    latency: '0.5초',
  },
  {
    id: 'vicuna-33b',
    name: 'Vicuna 33B',
    provider: 'LMSYS',
    providerIcon: '🦙',
    category: 'chat',
    inputPrice: 792,
    outputPrice: 792,
    contextWindow: 2048,
    maxOutput: 2048,
    latency: '1.1초',
  },
  {
    id: 'vicuna-13b',
    name: 'Vicuna 13B',
    provider: 'LMSYS',
    providerIcon: '🦙',
    category: 'chat',
    inputPrice: 300,
    outputPrice: 300,
    contextWindow: 2048,
    maxOutput: 2048,
    latency: '0.7초',
  },
  {
    id: 'alpaca-7b',
    name: 'Alpaca 7B',
    provider: 'Stanford',
    providerIcon: '🦙',
    category: 'chat',
    inputPrice: 264,
    outputPrice: 264,
    contextWindow: 2048,
    maxOutput: 2048,
    latency: '0.5초',
  },
  {
    id: 'bloom-176b',
    name: 'BLOOM 176B',
    provider: 'BigScience',
    providerIcon: '🌸',
    category: 'chat',
    inputPrice: 2640,
    outputPrice: 7920,
    contextWindow: 2048,
    maxOutput: 2048,
    latency: '2.5초',
  },
  {
    id: 'gpt-j-6b',
    name: 'GPT-J 6B',
    provider: 'EleutherAI',
    providerIcon: '⚡',
    category: 'completion',
    inputPrice: 200,
    outputPrice: 200,
    contextWindow: 2048,
    maxOutput: 2048,
    latency: '0.6초',
  },
  {
    id: 'gpt-neox-20b',
    name: 'GPT-NeoX 20B',
    provider: 'EleutherAI',
    providerIcon: '⚡',
    category: 'completion',
    inputPrice: 528,
    outputPrice: 528,
    contextWindow: 2048,
    maxOutput: 2048,
    latency: '1.0초',
  },
  {
    id: 'redpajama-incite-7b',
    name: 'RedPajama INCITE 7B',
    provider: 'Together',
    providerIcon: '🔴',
    category: 'chat',
    inputPrice: 264,
    outputPrice: 264,
    contextWindow: 2048,
    maxOutput: 2048,
    latency: '0.6초',
  },
  {
    id: 'mpt-30b',
    name: 'MPT-30B',
    provider: 'MosaicML',
    providerIcon: '🎼',
    category: 'chat',
    inputPrice: 792,
    outputPrice: 792,
    contextWindow: 8192,
    maxOutput: 8192,
    latency: '1.0초',
  },
  {
    id: 'mpt-7b',
    name: 'MPT-7B',
    provider: 'MosaicML',
    providerIcon: '🎼',
    category: 'chat',
    inputPrice: 264,
    outputPrice: 264,
    contextWindow: 2048,
    maxOutput: 2048,
    latency: '0.5초',
  },
];

export const providers = [
  '전체',
  'OpenAI',
  'Anthropic',
  'Google',
  'Meta',
  'Mistral',
  'Cohere',
  'DeepSeek',
  '기타',
];

export const categories = [
  '전체',
  'chat',
  'completion',
  'embedding',
  'image',
  'audio',
  'code',
];

export const mockAPIKeys: APIKey[] = [
  {
    id: 'key-1',
    name: 'Production API Key',
    key: 'sk-proj-abc...xyz',
    created: '2025-01-15',
    lastUsed: '2026-03-02',
    status: 'active',
  },
  {
    id: 'key-2',
    name: 'Development API Key',
    key: 'sk-proj-dev...123',
    created: '2025-02-01',
    lastUsed: '2026-03-01',
    status: 'active',
  },
  {
    id: 'key-3',
    name: 'Test API Key',
    key: 'sk-proj-test...789',
    created: '2025-02-20',
    lastUsed: '2026-02-28',
    status: 'active',
  },
  {
    id: 'key-4',
    name: 'Old API Key',
    key: 'sk-proj-old...456',
    created: '2024-11-10',
    lastUsed: '2025-12-25',
    status: 'revoked',
  },
];

export const mockUsageStats: UsageStat[] = Array.from({ length: 30 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (29 - i));
  const dateStr = date.toISOString().split('T')[0];

  return {
    date: dateStr,
    requests: Math.floor(Math.random() * 5000) + 1000,
    tokens: Math.floor(Math.random() * 10000000) + 2000000,
    cost: Math.floor(Math.random() * 500000) + 100000,
  };
});

export const mockMonthlyUsage = [
  { month: '2025-10', requests: 85000, tokens: 185000000, cost: 3200000 },
  { month: '2025-11', requests: 92000, tokens: 205000000, cost: 3800000 },
  { month: '2025-12', requests: 110000, tokens: 245000000, cost: 4500000 },
  { month: '2026-01', requests: 125000, tokens: 280000000, cost: 5200000 },
  { month: '2026-02', requests: 138000, tokens: 310000000, cost: 5800000 },
  { month: '2026-03', requests: 45000, tokens: 98000000, cost: 1850000 },
];

export const mockModelUsageBreakdown: ModelUsage[] = [
  { model: 'GPT-4o', requests: 35000, tokens: 78000000, cost: 850000 },
  { model: 'Claude Sonnet 4.5', requests: 28000, tokens: 62000000, cost: 720000 },
  { model: 'Gemini 2.5 Pro', requests: 22000, tokens: 48000000, cost: 580000 },
  { model: 'GPT-4.1 mini', requests: 18000, tokens: 40000000, cost: 320000 },
  { model: 'Claude Haiku 4.5', requests: 15000, tokens: 33000000, cost: 280000 },
];
