import type { LLMModel } from './types';

export const mockModels: LLMModel[] = [
  // Anthropic (Bedrock) - 10% 할인
  {
    id: 'bedrock/claude-opus-4.6',
    name: 'Claude Opus 4.6',
    provider: 'Anthropic (Bedrock)',
    providerIcon: '🧠',
    category: 'chat',
    inputPrice: 6503,
    outputPrice: 32513,
    contextWindow: 1000000,
    maxOutput: 128000,
    latency: '1.2초',
  },
  {
    id: 'bedrock/claude-sonnet-4.6',
    name: 'Claude Sonnet 4.6',
    provider: 'Anthropic (Bedrock)',
    providerIcon: '🧠',
    category: 'chat',
    inputPrice: 2167,
    outputPrice: 10838,
    contextWindow: 1000000,
    maxOutput: 128000,
    latency: '0.8초',
  },
  {
    id: 'bedrock/claude-haiku-4.5',
    name: 'Claude Haiku 4.5',
    provider: 'Anthropic (Bedrock)',
    providerIcon: '🧠',
    category: 'chat',
    inputPrice: 578,
    outputPrice: 2890,
    contextWindow: 1000000,
    maxOutput: 128000,
    latency: '0.4초',
  },

  // OpenAI
  {
    id: 'openai/gpt-5.3',
    name: 'GPT-5.3',
    provider: 'OpenAI',
    providerIcon: '🤖',
    category: 'chat',
    inputPrice: 7225,
    outputPrice: 36125,
    contextWindow: 2000000,
    maxOutput: 128000,
    latency: '1.0초',
  },
  {
    id: 'openai/gpt-5.1',
    name: 'GPT-5.1',
    provider: 'OpenAI',
    providerIcon: '🤖',
    category: 'chat',
    inputPrice: 1806,
    outputPrice: 14450,
    contextWindow: 1000000,
    maxOutput: 64000,
    latency: '0.7초',
  },
  {
    id: 'openai/gpt-5-nano',
    name: 'GPT-5 Nano',
    provider: 'OpenAI',
    providerIcon: '🤖',
    category: 'chat',
    inputPrice: 72,
    outputPrice: 578,
    contextWindow: 200000,
    maxOutput: 16000,
    latency: '0.3초',
  },
  {
    id: 'openai/o1-pro',
    name: 'o1-pro',
    provider: 'OpenAI',
    providerIcon: '🤖',
    category: 'chat',
    inputPrice: 216750,
    outputPrice: 867000,
    contextWindow: 200000,
    maxOutput: 100000,
    latency: '5.0초',
  },
  {
    id: 'openai/o3-mini',
    name: 'o3-mini',
    provider: 'OpenAI',
    providerIcon: '🤖',
    category: 'chat',
    inputPrice: 289,
    outputPrice: 1156,
    contextWindow: 200000,
    maxOutput: 65536,
    latency: '0.6초',
  },

  // Google Gemini
  {
    id: 'google/gemini-3.1-pro',
    name: 'Gemini 3.1 Pro',
    provider: 'Google',
    providerIcon: '💎',
    category: 'chat',
    inputPrice: 1445,
    outputPrice: 5780,
    contextWindow: 1000000,
    maxOutput: 8192,
    latency: '0.8초',
  },
  {
    id: 'google/gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'Google',
    providerIcon: '💎',
    category: 'chat',
    inputPrice: 434,
    outputPrice: 3613,
    contextWindow: 1000000,
    maxOutput: 8192,
    latency: '0.4초',
  },
  {
    id: 'google/gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'Google',
    providerIcon: '💎',
    category: 'chat',
    inputPrice: 289,
    outputPrice: 1156,
    contextWindow: 1000000,
    maxOutput: 8192,
    latency: '0.35초',
  },

  // xAI
  {
    id: 'xai/grok-4.1',
    name: 'Grok 4.1',
    provider: 'xAI',
    providerIcon: '🚀',
    category: 'chat',
    inputPrice: 1445,
    outputPrice: 7225,
    contextWindow: 2000000,
    maxOutput: 131072,
    latency: '0.9초',
  },
  {
    id: 'xai/grok-3',
    name: 'Grok 3',
    provider: 'xAI',
    providerIcon: '🚀',
    category: 'chat',
    inputPrice: 578,
    outputPrice: 2890,
    contextWindow: 200000,
    maxOutput: 32768,
    latency: '0.5초',
  },

  // Upstage - 100% 무료
  {
    id: 'upstage/solar-pro-3-beta',
    name: 'Solar Pro 3 Beta',
    provider: 'Upstage',
    providerIcon: '☀️',
    category: 'chat',
    inputPrice: 0,
    outputPrice: 0,
    contextWindow: 200000,
    maxOutput: 8192,
    latency: '0.6초',
  },
  {
    id: 'upstage/solar-pro-2',
    name: 'Solar Pro 2',
    provider: 'Upstage',
    providerIcon: '☀️',
    category: 'chat',
    inputPrice: 289,
    outputPrice: 867,
    contextWindow: 200000,
    maxOutput: 8192,
    latency: '0.55초',
  },

  // LG AI
  {
    id: 'lgai/exaone-4.0.1',
    name: 'EXAONE 4.0.1 32b',
    provider: 'LG AI',
    providerIcon: '🏢',
    category: 'chat',
    inputPrice: 433,
    outputPrice: 1300,
    contextWindow: 200000,
    maxOutput: 8192,
    latency: '0.7초',
  },

  // DeepSeek
  {
    id: 'deepseek/deepseek-v3.2',
    name: 'DeepSeek V3.2',
    provider: 'DeepSeek',
    providerIcon: '🔍',
    category: 'chat',
    inputPrice: 43,
    outputPrice: 289,
    contextWindow: 200000,
    maxOutput: 8192,
    latency: '0.5초',
  },

  // Perplexity
  {
    id: 'perplexity/sonar-reasoning-pro',
    name: 'Sonar Reasoning Pro',
    provider: 'Perplexity',
    providerIcon: '🔮',
    category: 'chat',
    inputPrice: 7225,
    outputPrice: 36125,
    contextWindow: 200000,
    maxOutput: 32768,
    latency: '2.0초',
  },
  {
    id: 'perplexity/sonar-pro',
    name: 'Sonar Pro',
    provider: 'Perplexity',
    providerIcon: '🔮',
    category: 'chat',
    inputPrice: 1445,
    outputPrice: 7225,
    contextWindow: 200000,
    maxOutput: 16384,
    latency: '1.2초',
  },
];
